---
- name: Get the System Kernel
  shell:
    uname -r
  register: result
- name: Print System Kernel
  debug:
    var: result
- name: Get HWE support status
  shell:
    hwe-support-status
  register: result
- name: Print HWE Support Status
  debug:
    var: result
- name: Install introvirt
  ansible.builtin.apt:
    name: 
      - libintrovirt1 
      - libintrovirt-doc
      - libintrovirt-dev
      - introvirt-tools
    state: present
  become: true
- name: Run ivversion
  shell:
    ivversion
  register: result
  become: true
- name: Print System Kernel
  debug:
    var: result