---
- name: Get the System Kernel
  shell:
    uname -r
  register: result
- name: Print System Kernel
  debug:
    var: result.stdout
- name: Install introvirt ppa
  ansible.builtin.apt_repository:
    repo: ppa:srpape/introvirt
    update_cache: true # apt-get update
  become: true
- name: Install lib ms pdb
  ansible.builtin.apt:
    name:
      - libmspdb1
      - libmspdb-dev
    state: present
  become: true
- name: Copy kvm introvirt deb
  ansible.builtin.copy:
    src: kvm-introvirt-5.4.0-135-generic_5.4.0-135.152-0.57.0~focal1_amd64.deb
    dest: /tmp/kvm-introvirt-5.4.0-135-generic_5.4.0-135.152-0.57.0~focal1_amd64.deb
  become: true
- name: Install kvm introvirt deb
  ansible.builtin.apt:
    deb: /tmp/kvm-introvirt-5.4.0-135-generic_5.4.0-135.152-0.57.0~focal1_amd64.deb
  become: true
