---
- name: Get the System Kernel
  shell:
    uname -r
  register: result
- name: Print System Kernel
  debug:
    var: result
- name: Get HWE support status
  shell:
    hwe-support-status
  register: result
- name: Print HWE Support Status
  debug:
    var: result
- name: Install introvirt ppa
  ansible.builtin.apt_repository:
    repo: ppa:srpape/introvirt
    update_cache: true # apt-get update
  become: true
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true
- name: Install lib ms pdb
  ansible.builtin.apt:
    name:
      - libmspdb1
      - libmspdb-dev
    state: present
  become: true
- name: Install kvm introvirt
  ansible.builtin.apt:
    name:
      - kvm-introvirt
      - kvm-introvirt-5.11.0-37-generic
    state: present
  become: true
- name: Install introvirt
  ansible.builtin.apt:
    name: 
      - libintrovirt1
      - libintrovirt-doc
      - libintrovirt-dev
      - introvirt-tools
    state: present
  become: true
- name: Run ivversion
  shell:
    ivversion
  register: result
  become: true
- name: Print System Kernel
  debug:
    var: result