name: macos test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos12_test:
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run System Check
        run: ./system-checks.sh
      - name: Run Ubuntu VM in VBox
        run: ./build-vbox-ubuntu.sh
#   macos11_test:
#     runs-on: macos-11
#     steps:
#      - run: ls -la
#      - run: ./check-vmx.sh