name: macos test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos12_test:
    runs-on: macos-12
    steps:
      - run: echo "Hello, World!"
      - run: sysctl -a | grep machdep.cpu
  macos11_test:
    runs-on: macos-11
    steps:
      - run: echo "Hello, World!"
      - run: sysctl -a | grep machdep.cpu
